version: "3.9"

services:
  auth-service:
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG:-latest}
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVICE_NAME: ${SERVICE_NAME:-auth-service}
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
      INTERNAL_SERVICE_NAME: ${INTERNAL_SERVICE_NAME:-auth-service}
      INTERNAL_ALLOWED_SERVICES: ${INTERNAL_ALLOWED_SERVICES}
    ports:
      - "8000:8000"
    networks:
      - school-network

networks:
  school-network:
    external: true
